apiVersion: v1
kind: Service
metadata:
  labels:
    name: db-service
    app: demo-voting-app
  name: db
spec:
  ports:
    - name: db-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
  type: ClusterIP
