apiVersion: v1
kind: Service
metadata:
  labels:
    name: result-service
    app: demo-voting-app
  name: result-service
spec:
  ports:
    - name: result-svc-port
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30005

  selector:
    name: result-app-pod
    app: demo-voting-app
  type: NodePort
