apiVersion: v1
kind: Service
metadata:
  labels:
    name: voting-service
    app: demo-voting-app
  name: voting-service
spec:
  ports:
    - name: voting-svc-port
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type: NodePort
